name: ricky_morty
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  json_serializable: ^6.9.5
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.10
  chopper: ^8.1.0
  auto_route: ^10.0.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  flutter_gen: ^5.10.0
  flutter_svg: ^2.1.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  dartz: ^0.10.1
  auto_mappr_annotation: ^2.3.0
  dropdown_button2: ^2.3.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.4
  internet_connection_checker: ^3.0.1
  cached_network_image: ^3.4.1
  freezed: ^2.5.8
  mockito: ^5.4.6




# uncomment for hive generator
#dependency_overrides:
#  source_gen: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  auto_mappr: ^2.8.0
  auto_route_generator: ^10.0.1
  flutter_gen_runner: ^5.10.0
#  hive_generator: ^2.0.1
  chopper_generator: ^8.1.0
  flutter_lints: ^5.0.0



flutter_gen:
  #  enabled: true

  output: lib/resources/assets
  line_length: 100

  # Optional
  integrations:
    flutter_svg: true

  fonts:
    outputs:
      package_parameter_enabled: true


flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  template_arbs_file: intl_en.arb
  output_dir: lib/resources/l10n
  class_name: AppLocalizations

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_Black.ttf
        - asset: assets/fonts/inter/Inter_BlackItalic.ttf
          style: italic
        - asset: assets/fonts/inter/Inter_ExtraBold.ttf
        - asset: assets/fonts/inter/Inter_ExtraBoldItalic.ttf
          style: italic
        - asset: assets/fonts/inter/Inter_Bold.ttf
        - asset: assets/fonts/inter/Inter_BoldItalic.ttf
          style: italic
        - asset: assets/fonts/inter/Inter_Light.ttf
        - asset: assets/fonts/inter/Inter_LightItalic.ttf
          style: italic
        - asset: assets/fonts/inter/Inter_Regular.ttf
        - asset: assets/fonts/inter/Inter_Italic.ttf
          style: italic
